using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media.Animation;
using System.Windows.Media;
using System.Windows.Input;
using HD2ModManager.ViewModels;

namespace HD2ModManager.Views
{
    // This class is generated by XAML compilation
    public partial class LibraryPageView : UserControl
    {
        public LibraryPageView()
        {
            InitializeComponent();
            Loaded += LibraryPageView_Loaded;
        }

        private void LibraryPageView_Loaded(object sender, RoutedEventArgs e)
        {
            EnsureVM();
        }
        public LibraryPageViewModel? VM { get; private set; }

        private void EnsureVM()
        {
            if (DataContext is LibraryPageViewModel existing)
            {
                VM = existing;
                return;
            }

            if (VM == null)
            {
                var shell = (Application.Current?.MainWindow as MainWindow)?.DataContext as HD2ModManager.ViewModels.ShellViewModel;
                if (shell == null) return;
                VM = new LibraryPageViewModel(shell.LibraryService, shell.Selection, shell.ProfileService);
                DataContext = VM;
            }
        }

        private void OnRenameModClick(object sender, RoutedEventArgs e)
        {
            EnsureVM();
            var card = GetCard(sender);
            if (card == null) return;
            var shell = (Application.Current?.MainWindow as MainWindow)?.DataContext as ShellViewModel;
            shell?.BeginBottomBarNameEdit(card.Mod.Guid, card.Mod.Name);
        }

        private void OnOpenDetailsClick(object sender, RoutedEventArgs e)
        {
            EnsureVM();
            var card = GetCard(sender);
            if (card == null) return;
            var shell = (Application.Current?.MainWindow as MainWindow)?.DataContext as HD2ModManager.ViewModels.ShellViewModel;
            shell?.OpenModDetailsFromPage(VM, card.Mod.Guid);
        }

        private void OnOpenDetailsOnRightClick(object sender, MouseButtonEventArgs e)
        {
            OnOpenDetailsClick(sender, e);
            e.Handled = true;
        }

        private void OnRowActionMouseDown(object sender, System.Windows.Input.MouseButtonEventArgs e)
        {
            ClearTransientSelection();
        }

        private void OnListBackgroundMouseDown(object sender, System.Windows.Input.MouseButtonEventArgs e)
        {
            if (e.OriginalSource is DependencyObject source && FindAncestor<Border>(source)?.DataContext is ModCardViewModel card)
            {
                return;
            }
            ClearTransientSelection();
        }

        private static T? FindAncestor<T>(DependencyObject? current) where T : DependencyObject
        {
            while (current is not null)
            {
                if (current is T found) return found;
                current = VisualTreeHelper.GetParent(current);
            }
            return null;
        }

        private static void ClearTransientSelection()
        {
            if (Application.Current?.MainWindow?.DataContext is ShellViewModel shell)
                shell.ClearTransientSelection();
        }

        private void OnToggleSearchClick(object sender, RoutedEventArgs e)
        {
            if (HeaderSearchBox.Visibility == Visibility.Visible)
            {
                var fadeOut = new DoubleAnimation(0, TimeSpan.FromMilliseconds(140));
                fadeOut.Completed += (_, _) =>
                {
                    HeaderSearchBox.Visibility = Visibility.Collapsed;
                    HeaderTitle.Visibility = Visibility.Visible;
                    HeaderSummary.Visibility = Visibility.Visible;
                    HeaderTitle.BeginAnimation(OpacityProperty, new DoubleAnimation(1, TimeSpan.FromMilliseconds(160)));
                    HeaderSummary.BeginAnimation(OpacityProperty, new DoubleAnimation(1, TimeSpan.FromMilliseconds(160)));
                };
                HeaderSearchBox.BeginAnimation(OpacityProperty, fadeOut);
                var actionFadeOut = new DoubleAnimation(0, TimeSpan.FromMilliseconds(140));
                actionFadeOut.Completed += (_, _) => HeaderActionPanel.Visibility = Visibility.Collapsed;
                HeaderActionPanel.BeginAnimation(OpacityProperty, actionFadeOut);
                return;
            }

            var titleFadeOut = new DoubleAnimation(0, TimeSpan.FromMilliseconds(140));
            titleFadeOut.Completed += (_, _) => HeaderTitle.Visibility = Visibility.Collapsed;
            HeaderTitle.BeginAnimation(OpacityProperty, titleFadeOut);
            var summaryFadeOut = new DoubleAnimation(0, TimeSpan.FromMilliseconds(140));
            summaryFadeOut.Completed += (_, _) => HeaderSummary.Visibility = Visibility.Collapsed;
            HeaderSummary.BeginAnimation(OpacityProperty, summaryFadeOut);
            HeaderActionPanel.Visibility = Visibility.Visible;
            HeaderActionPanel.BeginAnimation(OpacityProperty, new DoubleAnimation(1, TimeSpan.FromMilliseconds(160)));
            HeaderSearchBox.Visibility = Visibility.Visible;
            HeaderSearchBox.BeginAnimation(OpacityProperty, new DoubleAnimation(1, TimeSpan.FromMilliseconds(160)));
            HeaderSearchBox.Focus();
        }

        private void OnToggleOutdatedFilterClick(object sender, RoutedEventArgs e)
        {
            EnsureVM();
            if (VM is not null) VM.ShowOnlyOutdated = !VM.ShowOnlyOutdated;
        }

        private void OnModRowClick(object sender, System.Windows.Input.MouseButtonEventArgs e)
        {
            if (e.OriginalSource is DependencyObject source && FindAncestor<Button>(source) != null) return;
            EnsureVM();
            if ((sender as FrameworkElement)?.DataContext is ModCardViewModel card)
            {
                VM?.SelectRow(card, System.Windows.Input.Keyboard.Modifiers);
                e.Handled = true;
            }
        }

        private static ModCardViewModel? GetCard(object sender)
        {
            return (sender as FrameworkElement)?.DataContext as ModCardViewModel;
        }

    }
}
