using System.Linq;
using System.Windows;
using System.Windows.Controls;
using HD2ModManager.ViewModels;

namespace HD2ModManager.Views
{
    // This class is generated by XAML compilation
    public partial class LibraryPageView : UserControl
    {
        public LibraryPageView()
        {
            InitializeComponent();
            Loaded += LibraryPageView_Loaded;
        }

        private void OnOpenModFolderClick(object sender, RoutedEventArgs e)
        {
            var card = (sender as System.Windows.Controls.MenuItem)?.DataContext as HD2ModManager.ViewModels.ModCardViewModel;
            if (card == null) return;
            try
            {
                var root = HD2ModManager.Services.SettingsService.GetModLibraryFolder();
                var rel = card.Mod.SourcePath ?? string.Empty;
                var abs = System.IO.Path.IsPathRooted(rel) ? rel : System.IO.Path.GetFullPath(System.IO.Path.Combine(root, rel.Replace('/', System.IO.Path.DirectorySeparatorChar)));
                if (!System.IO.Directory.Exists(abs)) System.IO.Directory.CreateDirectory(abs);
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo { FileName = abs, UseShellExecute = true });
            }
            catch { }
        }

        private void OnCardContextMenuKeyDown(object sender, System.Windows.Input.KeyEventArgs e)
        {
            var cm = sender as System.Windows.Controls.ContextMenu;
            var fe = cm?.PlacementTarget as FrameworkElement;
            var card = fe?.DataContext as HD2ModManager.ViewModels.ModCardViewModel;
            if (card == null) return;
            switch (e.Key)
            {
                case System.Windows.Input.Key.A:
                    OnAddToProfileClick(cm!, new RoutedEventArgs()); e.Handled = true; break;
                case System.Windows.Input.Key.O:
                    OnOpenModFolderClick(cm!, new RoutedEventArgs()); e.Handled = true; break;
                case System.Windows.Input.Key.R:
                    OnRenameModClick(cm!, new RoutedEventArgs()); e.Handled = true; break;
                case System.Windows.Input.Key.E:
                    OnEditDescriptionClick(cm!, new RoutedEventArgs()); e.Handled = true; break;
                case System.Windows.Input.Key.I:
                    OnEditImageClick(cm!, new RoutedEventArgs()); e.Handled = true; break;
                case System.Windows.Input.Key.T:
                    OnEditTagsPageClick(cm!, new RoutedEventArgs()); e.Handled = true; break;
                case System.Windows.Input.Key.D:
                    OnRemoveModClick(cm!, new RoutedEventArgs()); e.Handled = true; break;
            }
        }

        private void LibraryPageView_Loaded(object sender, RoutedEventArgs e)
        {
            EnsureVM();
        }
        public LibraryPageViewModel? VM { get; private set; }

        private void EnsureVM()
        {
            if (VM == null)
            {
                var shell = (Application.Current?.MainWindow as MainWindow)?.DataContext as HD2ModManager.ViewModels.ShellViewModel;
                if (shell == null) return;
                VM = new LibraryPageViewModel(shell.LibraryService);
                DataContext = VM;
            }
        }

        private void OnSearch(object sender, RoutedEventArgs e)
        {
            EnsureVM();
            // Get QueryBox via name lookup
            if (this.FindName("QueryBox") is TextBox tb)
            {
                VM!.Query = tb.Text;
            }
        }

        private void OnRemoveModClick(object sender, RoutedEventArgs e)
        {
            EnsureVM();
            if (sender is System.Windows.Controls.MenuItem mi)
            {
                var card = (mi.DataContext as HD2ModManager.ViewModels.ModCardViewModel);
                // call VM private method via reflection or expose a public wrapper; we will replicate the remove here
                if (card != null)
                {
                    try
                    {
                        var shell = (Application.Current?.MainWindow as MainWindow)?.DataContext as HD2ModManager.ViewModels.ShellViewModel;
                        var lib = shell?.LibraryService;
                        if (lib != null)
                        {
                            var root = HD2ModManager.Services.SettingsService.GetModLibraryFolder();
                            var rel = card.Mod.SourcePath ?? string.Empty;
                            var abs = System.IO.Path.IsPathRooted(rel) ? rel : System.IO.Path.GetFullPath(System.IO.Path.Combine(root, rel.Replace('/', System.IO.Path.DirectorySeparatorChar)));
                            try { if (System.IO.Directory.Exists(abs)) System.IO.Directory.Delete(abs, true); } catch { }
                            lib.Remove(card.Mod.Guid);
                            lib.Save();
                        }
                    }
                    catch { }
                    VM!.Refresh();
                }
            }
        }

        

        private void OnRenameModClick(object sender, RoutedEventArgs e)
        {
            EnsureVM();
            var mi = sender as System.Windows.Controls.MenuItem;
            var card = mi?.DataContext as HD2ModManager.ViewModels.ModCardViewModel;
            if (card == null) return;
            var oldName = card.Mod.Name;
            var newName = Microsoft.VisualBasic.Interaction.InputBox("输入新名称:", "Rename", oldName);
            if (string.IsNullOrWhiteSpace(newName) || newName == oldName) return;
            try
            {
                var shell = (Application.Current?.MainWindow as MainWindow)?.DataContext as HD2ModManager.ViewModels.ShellViewModel;
                var lib = shell?.LibraryService;
                if (lib != null)
                {
                    var ok = lib.Rename(card.Mod.Guid, newName);
                    if (ok)
                    {
                        HD2ModManager.Services.LogService.Info($"UI rename ok for {card.Mod.Guid} -> {newName}");
                        var refreshed = lib.Get(card.Mod.Guid);
                        if (refreshed != null)
                        {
                            card.Mod.Name = refreshed.Name;
                            card.Mod.SourcePath = refreshed.SourcePath;
                        }
                    }
                    else
                    {
                        HD2ModManager.Services.LogService.Error($"UI rename failed for {card.Mod.Guid} -> {newName}");
                    }
                }
            }
            catch { }
            VM!.Refresh();
        }

        private void OnEditDescriptionClick(object sender, RoutedEventArgs e)
        {
            EnsureVM();
            var card = (sender as System.Windows.Controls.MenuItem)?.DataContext as HD2ModManager.ViewModels.ModCardViewModel;
            if (card == null) return;
            var newDesc = Microsoft.VisualBasic.Interaction.InputBox("编辑备注:", "Description", card.Mod.Description ?? string.Empty);
            card.Mod.Description = newDesc;
            var shell = (Application.Current?.MainWindow as MainWindow)?.DataContext as HD2ModManager.ViewModels.ShellViewModel;
            shell?.LibraryService.Add(card.Mod);
            shell?.LibraryService.Save();
            VM!.Refresh();
        }

        private void OnEditImageClick(object sender, RoutedEventArgs e)
        {
            EnsureVM();
            var card = (sender as System.Windows.Controls.MenuItem)?.DataContext as HD2ModManager.ViewModels.ModCardViewModel;
            if (card == null) return;
            var ofd = new Microsoft.Win32.OpenFileDialog
            {
                Filter = "Images|*.png;*.jpg;*.jpeg;*.webp;*.bmp|All files|*.*",
                Title = "选择图片"
            };
            if (ofd.ShowDialog() == true)
            {
                card.Mod.Image = ofd.FileName;
            }
            var shell = (Application.Current?.MainWindow as MainWindow)?.DataContext as HD2ModManager.ViewModels.ShellViewModel;
            shell?.LibraryService.Add(card.Mod);
            shell?.LibraryService.Save();
            VM!.Refresh();
        }


        private static string EnsureUniqueFolder(string baseDir)
        {
            var dir = baseDir;
            int i = 1;
            while (System.IO.Directory.Exists(dir))
            {
                dir = baseDir + "_" + i;
                i++;
            }
            return dir;
        }

        private static string SanitizeName(string name)
        {
            foreach (var ch in System.IO.Path.GetInvalidFileNameChars()) name = name.Replace(ch, '_');
            name = name.Trim();
            if (string.IsNullOrWhiteSpace(name)) name = "ImportedMod";
            return name;
        }

        private void OnEditTagsPageClick(object sender, RoutedEventArgs e)
        {
            var card = (sender as System.Windows.Controls.MenuItem)?.DataContext as HD2ModManager.ViewModels.ModCardViewModel;
            if (card == null) return;
            var shell = (Application.Current?.MainWindow as MainWindow)?.DataContext as HD2ModManager.ViewModels.ShellViewModel;
            if (shell == null) return;
            var vm = new HD2ModManager.ViewModels.TagEditPageViewModel(shell.LibraryService, card.Mod, new System.Collections.Generic.List<string>(), returnKey: "library");
            shell.CurrentPage = vm;
        }

        private void OnAddToProfileClick(object sender, RoutedEventArgs e)
        {
            var card = (sender as System.Windows.Controls.MenuItem)?.DataContext as HD2ModManager.ViewModels.ModCardViewModel;
            if (card == null) return;
            var shell = (Application.Current?.MainWindow as MainWindow)?.DataContext as HD2ModManager.ViewModels.ShellViewModel;
            var profile = shell?.ProfileService.Active;
            var activeKey = shell?.ProfileService.ActiveKey;
            if (profile == null || string.IsNullOrWhiteSpace(activeKey))
            {
                MessageBox.Show("未找到活动配置，请先创建或激活配置。", "Profile", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }
            if (!profile.Entries.Any(e => e.Guid == card.Mod.Guid))
            {
                profile.Entries.Add(new HD2ModManager.Models.ProfileEntry { Guid = card.Mod.Guid, Marker = 0 });
                shell!.ProfileService.Save(activeKey!);
                MessageBox.Show("已添加到当前配置。", "Profile", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            else
            {
                MessageBox.Show("该模组已在配置中。", "Profile", MessageBoxButton.OK, MessageBoxImage.Information);
            }
        }
    }
}
