//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HD2ModManager.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HD2ModManager.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 HD2 Mod Manager 的本地化字符串。
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HD2ModManager 的本地化字符串。
        /// </summary>
        public static string Breadcrumb_Home {
            get {
                return ResourceManager.GetString("Breadcrumb_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Common_Back {
            get {
                return ResourceManager.GetString("Common_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Common_Open {
            get {
                return ResourceManager.GetString("Common_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Library 的本地化字符串。
        /// </summary>
        public static string Home_ModLibrary {
            get {
                return ResourceManager.GetString("Home_ModLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Profile 的本地化字符串。
        /// </summary>
        public static string Home_NewProfile {
            get {
                return ResourceManager.GetString("Home_NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Home_Settings {
            get {
                return ResourceManager.GetString("Home_Settings", resourceCulture);
            }
        }

        public static string Profile_Active {
            get { return ResourceManager.GetString("Profile_Active", resourceCulture); }
        }
        public static string Profile_Delete {
            get { return ResourceManager.GetString("Profile_Delete", resourceCulture); }
        }
        public static string Profile_Disable {
            get { return ResourceManager.GetString("Profile_Disable", resourceCulture); }
        }
        public static string Profile_Enable {
            get { return ResourceManager.GetString("Profile_Enable", resourceCulture); }
        }
        public static string Profile_Rename {
            get { return ResourceManager.GetString("Profile_Rename", resourceCulture); }
        }

        public static string Home_AddDummyMod_Title {
            get { return ResourceManager.GetString("Home_AddDummyMod_Title", resourceCulture); }
        }
        public static string Home_AddDummyMod_Desc {
            get { return ResourceManager.GetString("Home_AddDummyMod_Desc", resourceCulture); }
        }
        public static string Home_SaveLibrary_Title {
            get { return ResourceManager.GetString("Home_SaveLibrary_Title", resourceCulture); }
        }
        public static string Home_SaveLibrary_Desc {
            get { return ResourceManager.GetString("Home_SaveLibrary_Desc", resourceCulture); }
        }
        public static string Home_LibraryStatus_Title {
            get { return ResourceManager.GetString("Home_LibraryStatus_Title", resourceCulture); }
        }
        public static string Home_LibraryStatus_Desc {
            get { return ResourceManager.GetString("Home_LibraryStatus_Desc", resourceCulture); }
        }
        public static string Home_ImportQueue_Title {
            get { return ResourceManager.GetString("Home_ImportQueue_Title", resourceCulture); }
        }
        public static string Home_ImportQueue_Desc {
            get { return ResourceManager.GetString("Home_ImportQueue_Desc", resourceCulture); }
        }

        public static string Integrity_LogGenerated {
            get { return ResourceManager.GetString("Integrity_LogGenerated", resourceCulture); }
        }

        public static string Notification_ImportComplete {
            get { return ResourceManager.GetString("Notification_ImportComplete", resourceCulture); }
        }

        public static string Notification_ImportFailed {
            get { return ResourceManager.GetString("Notification_ImportFailed", resourceCulture); }
        }

        public static string Notification_ImportQueueSummary {
            get { return ResourceManager.GetString("Notification_ImportQueueSummary", resourceCulture); }
        }

    }
}
