// <auto-generated />
using System;
using System.Globalization;
using System.Resources;

namespace ManagedMain.Resources
{
    public static class Strings
    {
        private static ResourceManager? _resourceManager;
        private static CultureInfo? _culture;

        public static ResourceManager ResourceManager => _resourceManager ??= new ResourceManager("ManagedMain.Resources.Strings", typeof(Strings).Assembly);
        public static CultureInfo? Culture { get => _culture; set => _culture = value; }

        // Toolbar buttons
        public static string SR_Btn_ImportFolder => ResourceManager.GetString("SR_Btn_ImportFolder", _culture) ?? "Import Folder";
        public static string SR_Btn_ImportArchive => ResourceManager.GetString("SR_Btn_ImportArchive", _culture) ?? "Import Archive";
        public static string SR_Btn_Delete => ResourceManager.GetString("SR_Btn_Delete", _culture) ?? "Delete";
        public static string SR_Btn_Export => ResourceManager.GetString("SR_Btn_Export", _culture) ?? "Export";
        public static string SR_Btn_Enable => ResourceManager.GetString("SR_Btn_Enable", _culture) ?? "Enable";
        public static string SR_Btn_Disable => ResourceManager.GetString("SR_Btn_Disable", _culture) ?? "Disable";
        public static string SR_Btn_NewMod => ResourceManager.GetString("SR_Btn_NewMod", _culture) ?? "New Mod";
        public static string SR_Btn_Save => ResourceManager.GetString("SR_Btn_Save", _culture) ?? "Save";

        // ManagedMainView toolbar
        public static string SR_Btn_New => ResourceManager.GetString("SR_Btn_New", _culture) ?? "New";
        public static string SR_Btn_Import => ResourceManager.GetString("SR_Btn_Import", _culture) ?? "Import";
        public static string SR_Btn_Copy => ResourceManager.GetString("SR_Btn_Copy", _culture) ?? "Copy";
        public static string SR_Btn_Close => ResourceManager.GetString("SR_Btn_Close", _culture) ?? "Close";
        public static string SR_Btn_SetGameFolder => ResourceManager.GetString("SR_Btn_SetGameFolder", _culture) ?? "Set Game Folder";
        public static string SR_Btn_SaveOptions => ResourceManager.GetString("SR_Btn_SaveOptions", _culture) ?? "Save";

        // Properties panel buttons
        public static string SR_Btn_Rename => ResourceManager.GetString("SR_Btn_Rename", _culture) ?? "Rename";
        public static string SR_Btn_CloseTab => ResourceManager.GetString("SR_Btn_CloseTab", _culture) ?? "Close Tab";
        public static string SR_Btn_OpenPath => ResourceManager.GetString("SR_Btn_OpenPath", _culture) ?? "Open Path";
        public static string SR_Btn_ChangePath => ResourceManager.GetString("SR_Btn_ChangePath", _culture) ?? "Change Path";

        // Titles
        public static string SR_Title_ModList => ResourceManager.GetString("SR_Title_ModList", _culture) ?? "Mod List";
        public static string SR_Title_Properties => ResourceManager.GetString("SR_Title_Properties", _culture) ?? "Properties";
        public static string SR_Title_Log => ResourceManager.GetString("SR_Title_Log", _culture) ?? "Log";
        public static string SR_Title_Profiles => ResourceManager.GetString("SR_Title_Profiles", _culture) ?? "Profiles";

        // Labels / tips
        public static string SR_Label_GameFolder => ResourceManager.GetString("SR_Label_GameFolder", _culture) ?? "Game Folder:";
        public static string SR_Tip_DoubleClickToOpen => ResourceManager.GetString("SR_Tip_DoubleClickToOpen", _culture) ?? "Tip: Double click a profile to open a tab.";

        // New additions for templates and hints
        public static string SR_Label_Path => ResourceManager.GetString("SR_Label_Path", _culture) ?? "Path";
        public static string SR_Btn_Status => ResourceManager.GetString("SR_Btn_Status", _culture) ?? "Status";
        public static string SR_Btn_LaunchGame => ResourceManager.GetString("SR_Btn_LaunchGame", _culture) ?? "Launch Game";
        public static string SR_Tip_NoProfilesHint => ResourceManager.GetString("SR_Tip_NoProfilesHint", _culture) ?? "No profiles yet. Click New or Import to create one.";
        public static string SR_Tip_DropHereToImport => ResourceManager.GetString("SR_Tip_DropHereToImport", _culture) ?? "Drop here to import";

        // Button labels inside mod detail templates
        public static string SR_Btn_Name => ResourceManager.GetString("SR_Btn_Name", _culture) ?? "Name";
        public static string SR_Btn_Remark => ResourceManager.GetString("SR_Btn_Remark", _culture) ?? "Remark";
        public static string SR_Btn_Image => ResourceManager.GetString("SR_Btn_Image", _culture) ?? "Image";
        public static string SR_Btn_Link => ResourceManager.GetString("SR_Btn_Link", _culture) ?? "Link";
        public static string SR_Btn_Open => ResourceManager.GetString("SR_Btn_Open", _culture) ?? "Open";

        // Labels in stats blocks
        public static string SR_Label_EnableState => ResourceManager.GetString("SR_Label_EnableState", _culture) ?? "Enable State";
        public static string SR_Label_OptionCount => ResourceManager.GetString("SR_Label_OptionCount", _culture) ?? "Options";
        public static string SR_Label_SubOptionCount => ResourceManager.GetString("SR_Label_SubOptionCount", _culture) ?? "Sub options";
        public static string SR_Label_FileGroupCount => ResourceManager.GetString("SR_Label_FileGroupCount", _culture) ?? "File groups";

        // Tooltips
        public static string SR_Tip_ToggleEnable => ResourceManager.GetString("SR_Tip_ToggleEnable", _culture) ?? "Click to toggle enable/disable";
        public static string SR_Tip_HoverPreview => ResourceManager.GetString("SR_Tip_HoverPreview", _culture) ?? "Hover to preview";

        // Dialogs
        public static string SR_Title_EditRemark => ResourceManager.GetString("SR_Title_EditRemark", _culture) ?? "Edit Remark";
        public static string SR_Title_Rename => ResourceManager.GetString("SR_Title_Rename", _culture) ?? "Rename";
        public static string SR_Btn_OK => ResourceManager.GetString("SR_Btn_OK", _culture) ?? "OK";
        public static string SR_Btn_Cancel => ResourceManager.GetString("SR_Btn_Cancel", _culture) ?? "Cancel";

        // Status drawer
        public static string SR_Status_OnlyIssues => ResourceManager.GetString("SR_Status_OnlyIssues", _culture) ?? "Only Issues";
        public static string SR_Btn_Refresh => ResourceManager.GetString("SR_Btn_Refresh", _culture) ?? "Refresh";
        public static string SR_Tip_DoubleClickCopyPath => ResourceManager.GetString("SR_Tip_DoubleClickCopyPath", _culture) ?? "Double click row to copy path";
        public static string SR_Col_Owner => ResourceManager.GetString("SR_Col_Owner", _culture) ?? "Owner";
        public static string SR_Col_Hex => ResourceManager.GetString("SR_Col_Hex", _culture) ?? "Hex";
        public static string SR_Col_ModList => ResourceManager.GetString("SR_Col_ModList", _culture) ?? "ModList";
        public static string SR_Col_Game => ResourceManager.GetString("SR_Col_Game", _culture) ?? "Game";
        public static string SR_Col_Exists => ResourceManager.GetString("SR_Col_Exists", _culture) ?? "Exists";
        public static string SR_Col_AllLinked => ResourceManager.GetString("SR_Col_AllLinked", _culture) ?? "All";
        public static string SR_Col_Count => ResourceManager.GetString("SR_Col_Count", _culture) ?? "Count";
        public static string SR_Col_Link => ResourceManager.GetString("SR_Col_Link", _culture) ?? "Link";
        public static string SR_Col_GameFile => ResourceManager.GetString("SR_Col_GameFile", _culture) ?? "GameFile";
        public static string SR_Msg_CopiedPath => ResourceManager.GetString("SR_Msg_CopiedPath", _culture) ?? "Copied: {0}";
        public static string SR_Status_Missing => ResourceManager.GetString("SR_Status_Missing", _culture) ?? "Missing: file not found in game folder";
        public static string SR_Status_Incomplete => ResourceManager.GetString("SR_Status_Incomplete", _culture) ?? "Incomplete: some files are missing in game folder";
        public static string SR_Status_SeqGap => ResourceManager.GetString("SR_Status_SeqGap", _culture) ?? "Sequence gap: game did not load files after a gap";
        public static string SR_Status_Duplicate => ResourceManager.GetString("SR_Status_Duplicate", _culture) ?? "Duplicate: multiple candidates with identical content";
        public static string SR_Status_PatchMismatch => ResourceManager.GetString("SR_Status_PatchMismatch", _culture) ?? "Patch N mismatch: game file N differs from mod list";
        public static string SR_Status_Normal => ResourceManager.GetString("SR_Status_Normal", _culture) ?? "Normal";
        public static string SR_Status_ExtraTip => ResourceManager.GetString("SR_Status_ExtraTip", _culture) ?? "Extra: game has a file with no corresponding mod entry";

        // Logs/messages
        public static string SR_Log_ClickLaunchGame_ProfileModsView => ResourceManager.GetString("SR_Log_ClickLaunchGame_ProfileModsView", _culture) ?? "Click launch game (ProfileModsView)";
        public static string SR_Log_ClickLaunchGame_Fallback => ResourceManager.GetString("SR_Log_ClickLaunchGame_Fallback", _culture) ?? "Click launch game (fallback)";
        public static string SR_Log_AutoDetectGameFolder => ResourceManager.GetString("SR_Log_AutoDetectGameFolder", _culture) ?? "Auto-detected game folder: {0}";
        public static string SR_Log_StatusDrawerToggleFailed => ResourceManager.GetString("SR_Log_StatusDrawerToggleFailed", _culture) ?? "Failed to open status drawer: {0}";
        public static string SR_Log_DragImportFailed => ResourceManager.GetString("SR_Log_DragImportFailed", _culture) ?? "Import by drag failed: {0}";
        public static string SR_Log_ImportedArchives => ResourceManager.GetString("SR_Log_ImportedArchives", _culture) ?? "Imported archives: {0}";
        public static string SR_Log_ImportedFolders => ResourceManager.GetString("SR_Log_ImportedFolders", _culture) ?? "Imported folders: {0}";
        public static string SR_Log_NoSelection => ResourceManager.GetString("SR_Log_NoSelection", _culture) ?? "No target selected";
        public static string SR_Log_NotFoundParentMain => ResourceManager.GetString("SR_Log_NotFoundParentMain", _culture) ?? "Cannot find parent Main";
        public static string SR_Log_NotFoundParentMainOption => ResourceManager.GetString("SR_Log_NotFoundParentMainOption", _culture) ?? "Cannot find parent Main/Option";
        public static string SR_Log_ImageUpdated => ResourceManager.GetString("SR_Log_ImageUpdated", _culture) ?? "Image updated";
        public static string SR_Log_SetImageFailed => ResourceManager.GetString("SR_Log_SetImageFailed", _culture) ?? "Set image failed: {0}";
        public static string SR_Log_UnrecognizedPatch => ResourceManager.GetString("SR_Log_UnrecognizedPatch", _culture) ?? "Unrecognized patch files";
        public static string SR_Log_UnsupportedTarget => ResourceManager.GetString("SR_Log_UnsupportedTarget", _culture) ?? "Unsupported target";
        public static string SR_Log_AddedFileGroups => ResourceManager.GetString("SR_Log_AddedFileGroups", _culture) ?? "Added file groups: {0}";
        public static string SR_Log_AddFileGroupsFailed => ResourceManager.GetString("SR_Log_AddFileGroupsFailed", _culture) ?? "Add file groups failed: {0}";

        // ManagedMainView stats and hints
        public static string SR_Label_Mods => ResourceManager.GetString("SR_Label_Mods", _culture) ?? "Mods";
        public static string SR_Label_PatchGroups => ResourceManager.GetString("SR_Label_PatchGroups", _culture) ?? "Patch Groups";
        public static string SR_Label_EnabledPatchGroups => ResourceManager.GetString("SR_Label_EnabledPatchGroups", _culture) ?? "Enabled Patch Groups";
        public static string SR_Tip_ProfileTreeUsage => ResourceManager.GetString("SR_Tip_ProfileTreeUsage", _culture) ?? "Double-click to open a profile tab. Left-click to select, right-click to deselect. Hold Shift or Ctrl for multi-select.";

        // GameLauncher logs
        public static string SR_Log_LaunchGame => ResourceManager.GetString("SR_Log_LaunchGame", _culture) ?? "Launch game";
        public static string SR_Log_LaunchGame_Protocol => ResourceManager.GetString("SR_Log_LaunchGame_Protocol", _culture) ?? "Launching via Steam protocol";
        public static string SR_Log_NoSteamRoot => ResourceManager.GetString("SR_Log_NoSteamRoot", _culture) ?? "Steam installation folder not found. Please install and sign in to Steam.";
        public static string SR_Log_SteamExeNotFound => ResourceManager.GetString("SR_Log_SteamExeNotFound", _culture) ?? "steam.exe not found in {0}";
        public static string SR_Log_LaunchGame_SteamExe => ResourceManager.GetString("SR_Log_LaunchGame_SteamExe", _culture) ?? "Launching via Steam (steam.exe)";
        public static string SR_Log_LaunchGame_Failed => ResourceManager.GetString("SR_Log_LaunchGame_Failed", _culture) ?? "Launch failed: {0}";

        // ManagedMainViewModel logs/messages
        public static string SR_Log_DifferentDriveHint => ResourceManager.GetString("SR_Log_DifferentDriveHint", _culture) ?? "Hint: For reliable links and to save disk space, consider placing the profile folder on the same drive as the game folder.";
        public static string SR_Log_GameFolderNotConfigured => ResourceManager.GetString("SR_Log_GameFolderNotConfigured", _culture) ?? "Game folder not configured";
        public static string SR_Log_EnableProfile_Starting => ResourceManager.GetString("SR_Log_EnableProfile_Starting", _culture) ?? "Enabling profile: {0} (normalize and rebuild links)...";
        public static string SR_Log_EnableProfile_Saved => ResourceManager.GetString("SR_Log_EnableProfile_Saved", _culture) ?? "Normalized patch numbers and files saved";
        public static string SR_Log_EnableProfile_Done => ResourceManager.GetString("SR_Log_EnableProfile_Done", _culture) ?? "Enabled profile: {0}";
        public static string SR_Log_EnableProfile_Failed => ResourceManager.GetString("SR_Log_EnableProfile_Failed", _culture) ?? "Enable failed: {0}";
        public static string SR_Log_DisableProfile_Starting => ResourceManager.GetString("SR_Log_DisableProfile_Starting", _culture) ?? "Disabling profile: {0}...";
        public static string SR_Log_DisableProfile_Saved => ResourceManager.GetString("SR_Log_DisableProfile_Saved", _culture) ?? "Normalized and saved";
        public static string SR_Log_DisableProfile_Done => ResourceManager.GetString("SR_Log_DisableProfile_Done", _culture) ?? "Disabled. Removed {0} files";
        public static string SR_Log_DisableProfile_Failed => ResourceManager.GetString("SR_Log_DisableProfile_Failed", _culture) ?? "Disable failed: {0}";
        public static string SR_Log_OpenTab => ResourceManager.GetString("SR_Log_OpenTab", _culture) ?? "Opened tab: {0}";
        public static string SR_Log_NewProfile => ResourceManager.GetString("SR_Log_NewProfile", _culture) ?? "New profile: {0}";
        public static string SR_Log_Tip_DoubleClickToEdit => ResourceManager.GetString("SR_Log_Tip_DoubleClickToEdit", _culture) ?? "Tip: Double-click the profile to enter Mod editing.";
        public static string SR_Log_NewProfile_Failed => ResourceManager.GetString("SR_Log_NewProfile_Failed", _culture) ?? "Create failed: {0}";
        public static string SR_Dlg_ImportProfile_Title => ResourceManager.GetString("SR_Dlg_ImportProfile_Title", _culture) ?? "Select the folder containing modlist.json (only set the location, no file reading)";
        public static string SR_Log_ImportProfile => ResourceManager.GetString("SR_Log_ImportProfile", _culture) ?? "Imported profile: {0}";
        public static string SR_Log_ImportProfile_Failed => ResourceManager.GetString("SR_Log_ImportProfile_Failed", _culture) ?? "Import failed: {0}";
        public static string SR_Log_CopyProfile_Starting => ResourceManager.GetString("SR_Log_CopyProfile_Starting", _culture) ?? "Copying profile {0} to {1}";
        public static string SR_Log_CopyProfile_Done => ResourceManager.GetString("SR_Log_CopyProfile_Done", _culture) ?? "Copy completed: {0} to {1}";
        public static string SR_Log_CopyProfile_Failed => ResourceManager.GetString("SR_Log_CopyProfile_Failed", _culture) ?? "Copy failed: {0}";
        public static string SR_Confirm_DeleteProfile_Message => ResourceManager.GetString("SR_Confirm_DeleteProfile_Message", _culture) ?? "This profile contains {0} Mods. Delete the folder? This operation cannot be undone.";
        public static string SR_Confirm_DeleteProfile_Title => ResourceManager.GetString("SR_Confirm_DeleteProfile_Title", _culture) ?? "Confirm Delete";
        public static string SR_Log_DeleteProfile_Starting => ResourceManager.GetString("SR_Log_DeleteProfile_Starting", _culture) ?? "Deleting profile: {0}";
        public static string SR_Log_DeleteProfile_Done => ResourceManager.GetString("SR_Log_DeleteProfile_Done", _culture) ?? "Deleted: {0}";
        public static string SR_Log_DeleteProfile_Failed => ResourceManager.GetString("SR_Log_DeleteProfile_Failed", _culture) ?? "Delete failed: {0}";
        public static string SR_Log_CloseTab => ResourceManager.GetString("SR_Log_CloseTab", _culture) ?? "Closed tab: {0}";
        public static string SR_Log_AutoGameFolderSet2 => ResourceManager.GetString("SR_Log_AutoGameFolderSet2", _culture) ?? "Auto-detected game folder: {0}. Click again to choose manually.";
        public static string SR_Log_AutoGameFolderNotFound2 => ResourceManager.GetString("SR_Log_AutoGameFolderNotFound2", _culture) ?? "Could not auto-detect game folder. Please choose manually.";
        public static string SR_Log_AutoGameFolderFailed2 => ResourceManager.GetString("SR_Log_AutoGameFolderFailed2", _culture) ?? "Auto-detect game folder failed. Please choose manually.";
        public static string SR_Dlg_SelectGameData_Desc => ResourceManager.GetString("SR_Dlg_SelectGameData_Desc", _culture) ?? "Select the Helldivers 2 data folder";
        public static string SR_Log_GameFolderSet2 => ResourceManager.GetString("SR_Log_GameFolderSet2", _culture) ?? "Game folder set: {0}";
        public static string SR_Log_InvalidName => ResourceManager.GetString("SR_Log_InvalidName", _culture) ?? "Invalid name";
        public static string SR_Log_DirExists => ResourceManager.GetString("SR_Log_DirExists", _culture) ?? "A folder with the same name already exists";
        public static string SR_Log_Rename_Done => ResourceManager.GetString("SR_Log_Rename_Done", _culture) ?? "Renamed: {0} -> {1}";
        public static string SR_Log_Rename_Failed => ResourceManager.GetString("SR_Log_Rename_Failed", _culture) ?? "Rename failed: {0}";
        public static string SR_Log_OpenPathFailed => ResourceManager.GetString("SR_Log_OpenPathFailed", _culture) ?? "Open path failed: {0}";
        public static string SR_Dlg_SelectNewProfileRoot_Desc => ResourceManager.GetString("SR_Dlg_SelectNewProfileRoot_Desc", _culture) ?? "Select new profile root folder";
        public static string SR_Dlg_PathSubOfOld => ResourceManager.GetString("SR_Dlg_PathSubOfOld", _culture) ?? "New path is a subfolder of the old path.";
        public static string SR_Dlg_PathParentOfOld => ResourceManager.GetString("SR_Dlg_PathParentOfOld", _culture) ?? "New path is a parent of the old path.";
        public static string SR_Dlg_PathChange_CannotTitle => ResourceManager.GetString("SR_Dlg_PathChange_CannotTitle", _culture) ?? "Cannot Change Path";
        public static string SR_Log_PathInvalid => ResourceManager.GetString("SR_Log_PathInvalid", _culture) ?? "Path invalid";
        public static string SR_Log_PathUnchanged => ResourceManager.GetString("SR_Log_PathUnchanged", _culture) ?? "Path unchanged";
        public static string SR_Log_PathUpdated => ResourceManager.GetString("SR_Log_PathUpdated", _culture) ?? "Path updated. Moved {0} items to new folder.";
        public static string SR_Log_MoveFailed => ResourceManager.GetString("SR_Log_MoveFailed", _culture) ?? "Move failed: {0}";
        public static string SR_Title_EditLink => ResourceManager.GetString("SR_Title_EditLink", _culture) ?? "Edit Link";
        public static string SR_Prompt_EnterUrl => ResourceManager.GetString("SR_Prompt_EnterUrl", _culture) ?? "Enter URL (start with http/https)";

        // New strongly-typed accessors for added keys
        public static string SR_Log_LinkUpdated => ResourceManager.GetString("SR_Log_LinkUpdated", _culture) ?? "Link updated";
        public static string SR_Log_EditLinkFailed => ResourceManager.GetString("SR_Log_EditLinkFailed", _culture) ?? "Edit link failed: {0}";
        public static string SR_Log_CreateOptionFolderFailed => ResourceManager.GetString("SR_Log_CreateOptionFolderFailed", _culture) ?? "Create option folder failed: {0}";
        public static string SR_Log_AddedOption => ResourceManager.GetString("SR_Log_AddedOption", _culture) ?? "Added option: {0}";
        public static string SR_Log_CreateSubOptionFolderFailed => ResourceManager.GetString("SR_Log_CreateSubOptionFolderFailed", _culture) ?? "Create suboption folder failed: {0}";
        public static string SR_Log_AddedSubOption => ResourceManager.GetString("SR_Log_AddedSubOption", _culture) ?? "Added suboption: {0}";
        public static string SR_Log_ImportingFolder => ResourceManager.GetString("SR_Log_ImportingFolder", _culture) ?? "Importing folder...";
        public static string SR_Log_ImportingArchive => ResourceManager.GetString("SR_Log_ImportingArchive", _culture) ?? "Importing archive...";
        public static string SR_Log_Imported => ResourceManager.GetString("SR_Log_Imported", _culture) ?? "Imported: {0}";
        public static string SR_Log_ImportFailed => ResourceManager.GetString("SR_Log_ImportFailed", _culture) ?? "Import failed: {0}";
        public static string SR_Log_CreatedEmptyMod => ResourceManager.GetString("SR_Log_CreatedEmptyMod", _culture) ?? "New empty Mod: {0}";
        public static string SR_Log_CreateModFailed => ResourceManager.GetString("SR_Log_CreateModFailed", _culture) ?? "Create Mod failed: {0}";
        public static string SR_Log_PleaseWait => ResourceManager.GetString("SR_Log_PleaseWait", _culture) ?? "Please wait...";
        public static string SR_Log_ProfileDisabled_SaveOnly_AndNotApply => ResourceManager.GetString("SR_Log_ProfileDisabled_SaveOnly_AndNotApply", _culture) ?? "Profile disabled. Saved modlist state only; not applied to game folder.";
        public static string SR_Log_ProfileDisabled_SaveOnly => ResourceManager.GetString("SR_Log_ProfileDisabled_SaveOnly", _culture) ?? "Profile disabled. Saved modlist state only.";
        public static string SR_Log_ApplyingEnable => ResourceManager.GetString("SR_Log_ApplyingEnable", _culture) ?? "Applying enable state...";
        public static string SR_Log_ApplyingDisable => ResourceManager.GetString("SR_Log_ApplyingDisable", _culture) ?? "Applying disable state...";
        public static string SR_Log_Done => ResourceManager.GetString("SR_Log_Done", _culture) ?? "Done.";
        public static string SR_Log_EnableFailed2 => ResourceManager.GetString("SR_Log_EnableFailed2", _culture) ?? "Enable failed: {0}";
        public static string SR_Log_DisableFailed2 => ResourceManager.GetString("SR_Log_DisableFailed2", _culture) ?? "Disable failed: {0}";
        public static string SR_Log_DeletedCount => ResourceManager.GetString("SR_Log_DeletedCount", _culture) ?? "Deleted {0} item(s)";
        public static string SR_Log_SelectAMod => ResourceManager.GetString("SR_Log_SelectAMod", _culture) ?? "Select a Mod";
        public static string SR_Log_RemarkUpdated => ResourceManager.GetString("SR_Log_RemarkUpdated", _culture) ?? "Remark updated";

        public static string SR_Dlg_SelectExtractedModFolder_Desc => ResourceManager.GetString("SR_Dlg_SelectExtractedModFolder_Desc", _culture) ?? "Select the extracted Mod folder";
        public static string SR_Dlg_SelectArchive_Title => ResourceManager.GetString("SR_Dlg_SelectArchive_Title", _culture) ?? "Select Mod archive (zip/7z/rar)";
        public static string SR_Dlg_Filter_Archives => ResourceManager.GetString("SR_Dlg_Filter_Archives", _culture) ?? "Archives|*.zip;*.7z;*.rar|All|*.*";
        public static string SR_Dlg_Filter_Images => ResourceManager.GetString("SR_Dlg_Filter_Images", _culture) ?? "Images|*.png;*.jpg;*.jpeg|All|*.*";
        public static string SR_Dlg_Ok => ResourceManager.GetString("SR_Dlg_Ok", _culture) ?? "OK";
        public static string SR_Dlg_Cancel => ResourceManager.GetString("SR_Dlg_Cancel", _culture) ?? "Cancel";
    }
}
